controllers/RoomArchiveController.php
<?php

namespace app\controllers;

use app\models\RoomSetting;
use app\models\RoomUser;
use app\models\RoomUserSearch;
use app\models\User;
use Yii;
use app\models\Room;
use app\models\RoomSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;

/**
 * RoomController implements the CRUD actions for Room model.
 */
class RoomArchiveController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Room models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new RoomSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['status' => Room::STATUS_END]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Room model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $request = Yii::$app->request;

        $searchModel = new RoomUserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['room_id' => $id]);

        if(Yii::$app->user->identity->isSuperAdmin() == false){
            $dataProvider->query->andWhere(['user_id' => Yii::$app->user->getId()]);
        }

        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;

            return [
                'title'=> "комната #".$id,
                'content'=>$this->renderAjax('view', [
                    'model' => $this->findModel($id),
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                ]),
                'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                    Html::a('Изменить',['update','id'=>$id],['class'=>'btn btn-primary','role'=>'modal-remote'])
            ];
        }else{
            return $this->render('view', [
                'model' => $this->findModel($id),
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
    }

    /**
     * Creates a new Room model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new Room();

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Добавить комнату",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                        Html::button('Создать',['class'=>'btn btn-primary','type'=>"submit"])

                ];
            }else if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>'#crud-datatable-pjax',
                    'title'=> "Добавить комнату",
                    'content'=>'<span class="text-success">Создание комнаты успешно завершено</span>',
                    'footer'=> Html::button('ОК',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                        Html::a('Создать еще',['create'],['class'=>'btn btn-primary','role'=>'modal-remote'])

                ];
            }else{
                return [
                    'title'=> "Добавить комнату",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                        Html::button('Создать',['class'=>'btn btn-primary','type'=>"submit"])

                ];
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }

    }

    /**
     * Updates an existing Room model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Изменить комнату #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                        Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];
            }else if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>'#crud-datatable-pjax',
                    'title'=> "комната #".$id,
                    'content'=>$this->renderAjax('view', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                        Html::a('Изменить',['update','id'=>$id],['class'=>'btn btn-primary','role'=>'modal-remote'])
                ];
            }else{
                return [
                    'title'=> "Изменить комнату #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                        Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     *
     */
    public function actionAutoCreate()
    {
        /** @var RoomSetting $settings */
        $settings = RoomSetting::find()->all();

        foreach ($settings as $setting)
        {
            $model = new Room([
                'name' => $setting->name,
                'status' => Room::STATUS_ACCEPT,
                'room_setting_id' => $setting->id,
                'service_commission' => $setting->commission,
                'diff_rate_one' => $setting->diff_rate_one,
                'diff_rate_two' => $setting->diff_rate_two,
                'datetime_accept_end' => date('Y-m-d H:i:s', time() + $setting->time_accept * 60),
                'datetime_end' => date('Y-m-d H:i:s', time() + $setting->time_await * 60),
                'min_value' => $setting->min_value,
                'max_value' => $setting->max_value,
            ]);

            $model->save(false);
        }
    }

    /**
     * @param int $room_id
     * @param string $reloadPjaxContainer
     * @return array|string|Response
     */
    public function actionAddUser($room_id, $reloadPjaxContainer = '#crud-datatable-pjax')
    {
        $request = Yii::$app->request;
        $model = new RoomUser();
        $model->room_id = $room_id;
        $model->user_id = Yii::$app->user->getId();

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Подать заявку",
                    'content'=>$this->renderAjax('@app/views/room-user/create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                        Html::button('Создать',['class'=>'btn btn-primary','type'=>"submit"])

                ];
            }else if($model->load($request->post()) && $model->save()){

                /** @var User $user */
                $user = Yii::$app->user->identity;
                $user->balance = $user->balance - $model->rate;

views/room-archive/_columns.php
<?php
use kartik\grid\GridView;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use app\models\Room;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
        // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'id',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'name',
        'content' => function($model){
            return Html::a($model->name, ['room-archive/view', 'id' => $model->id], ['data-pjax' => 0]);
        }
    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'room_setting_id',
//    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'datetime_accept_end',
        'format' => ['date', 'php:d.m.Y H:i:s'],
        'filterType' => GridView::FILTER_DATE_RANGE,
        'filterWidgetOptions' => [
            'convertFormat'=>true,
            'pluginOptions' => [
                'opens'=>'right',
                'locale' => [
                    'cancelLabel' => 'Clear',
                    'format' => 'Y-m-d',
                ]
            ]
        ],
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'datetime_end',
        'format' => ['date', 'php:d.m.Y H:i:s'],
        'filterType' => GridView::FILTER_DATE_RANGE,
        'filterWidgetOptions' => [
            'convertFormat'=>true,
            'pluginOptions' => [
                'opens'=>'right',
                'locale' => [
                    'cancelLabel' => 'Clear',
                    'format' => 'Y-m-d',
                ]
            ]
        ],
    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'service_commission',
//    ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'status',
         'value' => function($model){
            return ArrayHelper::getValue(Room::statusLabels(), $model->status);
         },
         'filter' => Room::statusLabels(),
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'min_value',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'max_value',
     ],
//     [
//         'class'=>'\kartik\grid\DataColumn',
//         'attribute'=>'diff_rate_one',
//     ],
//     [
//         'class'=>'\kartik\grid\DataColumn',
//         'attribute'=>'diff_rate_two',
//     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'created_at',
         'format' => ['date', 'php:d.m.Y H:i:s'],
         'filterType' => GridView::FILTER_DATE_RANGE,
         'filterWidgetOptions' => [
             'convertFormat'=>true,
             'pluginOptions' => [
                 'opens'=>'right',
                 'locale' => [
                     'cancelLabel' => 'Clear',
                     'format' => 'Y-m-d',
                 ]
             ]
         ],
     ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'label'=>'Кол-во пользователей',
        'content' => function($model){
            $roomUsers = array_unique(ArrayHelper::getColumn(\app\models\RoomUser::find()->where(['room_id' => $model->id])->all(), 'user_id'));
            return count($roomUsers);
        }
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'label'=>'Кол-во ставок',
        'content' => function($model){
            return \app\models\RoomUser::find()->where(['room_id' => $model->id])->count();
        }
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'label'=>'Сумма ставок',
        'content' => function($model){
            return \app\models\RoomUser::find()->where(['room_id' => $model->id])->sum('rate');
        }
    ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'template' => '{update}{delete}',
        'visible' => Yii::$app->user->identity->isSuperAdmin(),
        'buttons' => [
            'delete' => function ($url, $model) {
                return Html::a('<i class="fa fa-trash text-danger" style="font-size: 16px;"></i>', $url, [
                    'role'=>'modal-remote', 'title'=>'Удалить',
                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                    'data-request-method'=>'post',
                    'data-confirm-title'=>'Вы уверены?',
                    'data-confirm-message'=>'Вы действительно хотите удалить данную запись?'
                ]);
            },
            'update' => function ($url, $model) {
                return Html::a('<i class="fa fa-pencil text-primary" style="font-size: 16px;"></i>', $url, [
                    'role'=>'modal-remote', 'title'=>'Изменить',
                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                    'data-request-method'=>'post',
                ])."&nbsp;";
            }
        ],
    ],

];   

views/room-archive/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Room */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="room-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'room_setting_id')->textInput() ?>

    <?= $form->field($model, 'datetime_accept_end')->textInput() ?>

    <?= $form->field($model, 'datetime_end')->textInput() ?>

    <?= $form->field($model, 'service_commission')->textInput() ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <?= $form->field($model, 'min_value')->textInput() ?>

    <?= $form->field($model, 'max_value')->textInput() ?>

    <?= $form->field($model, 'diff_rate_one')->textInput() ?>

    <?= $form->field($model, 'diff_rate_two')->textInput() ?>

    <?= $form->field($model, 'created_at')->textInput() ?>

  
	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>

views/room-archive/_users_columns.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use app\models\User;
use app\models\RoomUser;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'id',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'user_id',
        'value' => 'user.login',
    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'room_id',
//    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'datetime_enter',
        'format' => ['date', 'php:d.m.Y H:i:s'],
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'rate',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'rate_type',
        'value' => function($model){
            return ArrayHelper::getValue(RoomUser::rateTypeLabels(), $model->rate_type);
        }
    ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'won',
         'value' => function($model){
            if($model->won === 1){
                return 'Победил';
            } else if($model->won === 0){
                return 'Не победил';
            } else if($model->won === 2){
                return 'Не участвовал';
            }
         }
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'get_payment',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'write_off',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'datetime_end',
         'format' => ['date', 'php:d.m.Y H:i:s'],
     ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) {
            return Url::to(["room-user/$action",'id'=>$key]);
        },
        'template' => '{update}{delete}',
        'visible' => Yii::$app->user->identity->isSuperAdmin(),
        'buttons' => [
            'delete' => function ($url, $model) {
                return Html::a('<i class="fa fa-trash text-danger" style="font-size: 16px;"></i>', $url, [
                    'role'=>'modal-remote', 'title'=>'Удалить',
                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                    'data-request-method'=>'post',
                    'data-confirm-title'=>'Вы уверены?',
                    'data-confirm-message'=>'Вы действительно хотите удалить данную запись?'
                ]);
            },
            'update' => function ($url, $model) {
                return Html::a('<i class="fa fa-pencil text-primary" style="font-size: 16px;"></i>', $url, [
                        'role'=>'modal-remote', 'title'=>'Изменить',
                        'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                        'data-request-method'=>'post',
                    ])."&nbsp;";
            }
        ],
    ],

];

views/room-archive/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Room */

?>
<div class="room-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/room-archive/index.php
<?php
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;

/* @var $this yii\web\View */
/* @var $searchModel app\models\RoomSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = "Комнаты";
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

$totalBalance = array_sum(ArrayHelper::getColumn($dataProvider->models, 'balance'));

?>
<div class="panel panel-inverse room-index">
    <div class="panel-heading">
<!--        <div class="panel-heading-btn">-->
<!--        </div>-->
        <h4 class="panel-title">Комнаты</h4>
        <span>Баланс площадки: <?= $totalBalance ?></span>
    </div>
    <div class="panel-body">
        <div id="ajaxCrudDatatable">
            <?=GridView::widget([
            'id'=>'crud-datatable',
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'pjax'=>true,
            'columns' => require(__DIR__.'/_columns.php'),
            'panelBeforeTemplate' => '',
            'striped' => true,
            'condensed' => true,
            'responsive' => true,
            'panel' => [
            'headingOptions' => ['style' => 'display: none;'],
            'after'=>BulkButtonWidget::widget([
            'buttons'=>Html::a('<i class="glyphicon glyphicon-trash"></i>&nbsp; Удалить',
            ["bulk-delete"] ,
            [
            "class"=>"btn btn-danger btn-xs",
            'role'=>'modal-remote-bulk',
            'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
            'data-request-method'=>'post',
            'data-confirm-title'=>'Вы уверены?',
            'data-confirm-message'=>'Вы действительно хотите удалить данный элемент?'
            ]),
            ]).
            '<div class="clearfix"></div>',
            ]
            ])?>
        </div>
    </div>
</div>

<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/room-archive/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Room */
?>
<div class="room-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/room-archive/users_index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset;
use johnitvn\ajaxcrud\BulkButtonWidget;

/* @var $this yii\web\View */
/* @var $searchModel app\models\RoomSettingSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */


?>

            <?=GridView::widget([
                'id'=>'crud-users-datatable',
                'dataProvider' => $dataProvider,
//                'filterModel' => $searchModel,
                'pjax'=>true,
                'columns' => require(__DIR__.'/_users_columns.php'),
                'panelBeforeTemplate' => '',
                'striped' => true,
                'condensed' => true,
                'responsive' => true,
                'panel' => ''
            ])?>

views/room-archive/view.php
<?php

use app\models\Room;
use yii\helpers\ArrayHelper;
use yii\widgets\DetailView;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use app\models\Course;
use yii\widgets\Pjax;
use yii\helpers\VarDumper;

/* @var $this yii\web\View */
/* @var $model app\models\Room */

$this->title = "Комната «{$model->name}»";

\johnitvn\ajaxcrud\CrudAsset::register($this);

?>
<div class="room-view">
    <div class="panel panel-inverse">
        <div class="panel-heading">
            <h4 class="panel-title">Комната</h4>
        </div>
        <div class="row">




            <!-- TradingView Widget END -->
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <p>
                            <?php if($model->status == 0): ?>
                                <?= Html::a('Подать заявку', ['room/add-user', 'room_id' => $model->id, 'reloadPjaxContainer' => '#crud-users-datatable-pjax'], ['class' => 'btn btn-primary', 'role' => 'modal-remote']) ?>
                            <?php endif; ?>
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-9">
                        <?= $this->render('users_index', [
                            'searchModel' => $searchModel,
                            'dataProvider' => $dataProvider,
                        ]) ?>
                    </div>
                    <div class="col-md-3">
                        <?= DetailView::widget([
                            'model' => $model,
                            'attributes' => [
                                'id',
                                'name',
//                                [
//                                    'label' => 'Настройка',
//                                    'value' => 'roomSetting.name',
//                                ],
                                'datetime_accept_end',
                                'datetime_end',
                                'service_commission',
                                [
                                    'label' => 'Статус',
                                    'value' => function($model){
                                        return ArrayHelper::getValue(Room::statusLabels(), $model->status);
                                    }
                                ],
                                'min_value',
                                'max_value',
                                'diff_rate_one',
                                'diff_rate_two',
                                'created_at',
                            ],
                        ]) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        window.setTimeout(function() {
            $('#f133').load('someScript.php');
        },100)
    </script>
    <script type="text/javascript">
        setInterval(function(){
            $.pjax.reload('#pjax-table-container');
        }, 60000);
        setInterval(function(){
            $.pjax.reload('#pjax-table2-container');
        }, 61000);
    </script>
    <?php Modal::begin([
        "id"=>"ajaxCrudModal",
        "footer"=>"",// always need it for jquery plugin
    ])?>
    <?php Modal::end(); ?>