models/Room.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "room".
 *
 * @property int $id
 * @property string $name Название
 * @property int $room_setting_id Настройка
 * @property string $datetime_accept_end Дата и время завершения приеам заявок
 * @property string $datetime_end Дата и время подведения итогов
 * @property double $service_commission Коммисия сервиса
 * @property double $balance Баланс площадки
 * @property int $status Статус
 * @property double $min_value Мин. значение
 * @property double $max_value Макс. значение
 * @property double $diff_rate_one Разница ставок 1
 * @property double $diff_rate_two Разница ставок 2
 * @property string $created_at
 * @property int $is_limit
 *
 * @property int $statusByTime
 *
 * @property RoomSetting $roomSetting
 * @property RoomUser[] $roomUsers
 */
class Room extends \yii\db\ActiveRecord
{
    const STATUS_ACCEPT = 0;
    const STATUS_AWAIT = 1;
    const STATUS_END = 2;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'room';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'updatedAtAttribute' => null,
                'createdAtAttribute' => 'created_at',
                'value' => date('Y-m-d H:i:s'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['room_setting_id', 'status', 'is_limit'], 'integer'],
            [['datetime_accept_end', 'datetime_end', 'created_at'], 'safe'],
            [['service_commission', 'min_value', 'max_value', 'diff_rate_one', 'diff_rate_two', 'balance'], 'number'],
            [['name'], 'string', 'max' => 255],
            [['room_setting_id'], 'exist', 'skipOnError' => true, 'targetClass' => RoomSetting::className(), 'targetAttribute' => ['room_setting_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'room_setting_id' => 'Настройка',
            'datetime_accept_end' => 'Дата и время завершения приема заявок',
            'datetime_end' => 'Дата и время подведения итогов',
            'service_commission' => 'Коммисия сервиса',
            'balance' => 'Баланс площадки',
            'status' => 'Статус',
            'min_value' => 'Мин. значение',
            'max_value' => 'Макс. значение',
            'diff_rate_one' => 'Разница ставок 1',
            'diff_rate_two' => 'Разница ставок 2',
            'created_at' => 'Создан',
            'is_limit' => 'Лимит'
        ];
    }

    /**
     * @return array
     */
    public static function statusLabels()
    {
        return [
            self::STATUS_ACCEPT => 'Прием заявок',
            self::STATUS_AWAIT => 'Ожидание результата',
            self::STATUS_END => 'Завершена',
        ];
    }

    /**
     * @return int
     */
    public function getStatusByTime()
    {
        if(date('Y-m-d H:i') > date('Y-m-d H:i',strtotime($this->datetime_accept_end))){
            if(date('Y-m-d H:i') > date('Y-m-d H:i',strtotime($this->datetime_end))){
                return self::STATUS_END;
            }
            return self::STATUS_AWAIT;
        }

        return self::STATUS_ACCEPT;
    }

    /**
     * @inheritdoc
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);

        if($insert){
            $this->name .= $this->id;
            $this->save(false);
        }
    }

    /**
     * @return string
     */
    public function getUntilDateTimeAcceptEndText()
    {
        $now = time();
        $diff = strtotime($this->datetime_accept_end) - $now;

        $diff = round($diff / 60);
        if($diff <= 0){
            return "--:--";
        }
        return strlen(strval($diff)) == 2 ? "00:{$diff}" : "00:0{$diff}м";

        // if($diff > 0){
        //     $interval = date_diff(new \DateTime($this->datetime_accept_end), new \DateTime(date('Y-m-d H:i:s', $now)));

        //     if($interval->days > 0){
        //         return $interval->format("%a дней %H:%Iм");
        //     } else {
        //         return $interval->format("%H:%Iм");
        //     }
        // } else {
        //     return '00:00';
        // }
    }

    /**
     * @return string
     */
    public function getUntilDateTimeEndText()
    {
        $now = time();
        $diff = strtotime($this->datetime_end) - $now;

        $diff = round($diff / 60);
        if($diff <= 0){
            return "--:--";
        }
        return strlen(strval($diff)) == 2 ? "00:{$diff}" : "00:0{$diff}м";

        // if($diff > 0){
        //     $interval = date_diff(new \DateTime($this->datetime_end), new \DateTime(date('Y-m-d H:i:s', $now + 60)));

        //     if($interval->days > 0){
        //         return $interval->format("%a дней %H:%Iм");
        //     } else {
        //         return $interval->format("%H:%Iм");
        //     }
        // } else {
        //     return '00:00';
        // }
    }

    /**
     * @return array|null|\yii\db\ActiveRecord
     */
    public function getCurrentUserRate()
    {
        return RoomUser::find()->where(['user_id' => Yii::$app->user->getId(), 'room_id' => $this->id])->one();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRoomSetting()
    {
        return $this->hasOne(RoomSetting::className(), ['id' => 'room_setting_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRoomUsers()
    {
        return $this->hasMany(RoomUser::className(), ['room_id' => 'id']);
    }
}

controllers/RoomController.php
<?php

namespace app\controllers;

use app\models\RoomSetting;
use app\models\RoomUser;
use app\models\RoomUserSearch;
use app\models\User;
use Yii;
use app\models\Room;
use app\models\RoomSearch;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;

/**
 * RoomController implements the CRUD actions for Room model.
 */
class RoomController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Room models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new RoomSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['!=', 'status', Room::STATUS_END]);

        $dataProvider->pagination = false;

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Displays a single Room model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $request = Yii::$app->request;

        $searchModel = new RoomUserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['room_id' => $id]);

        $upSearchModel = new RoomUserSearch();
        $upDataProvider = $upSearchModel->search(Yii::$app->request->queryParams);
        $upDataProvider->query->andWhere(['room_id' => $id, 'rate_type' => [RoomUser::RATE_TYPE_UP, RoomUser::RATE_TYPE_AWAIT_UP]]);

        $downSearchModel = new RoomUserSearch();
        $downDataProvider = $downSearchModel->search(Yii::$app->request->queryParams);
        $downDataProvider->query->andWhere(['room_id' => $id, 'rate_type' => [RoomUser::RATE_TYPE_DOWN, RoomUser::RATE_TYPE_AWAIT_DOWN]]);


        if(Yii::$app->user->identity->isSuperAdmin() == false){
            $dataProvider->query->andWhere(['user_id' => Yii::$app->user->getId()]);
        }

        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;

            return [
                'title'=> "комната #".$id,
                'content'=>$this->renderAjax('view', [
                    'model' => $this->findModel($id),
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                    'upSearchModel' => $upSearchModel,
                    'upDataProvider' => $upDataProvider,
                    'downSearchModel' => $downSearchModel,
                    'downDataProvider' => $downDataProvider,
                ]),
                'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                    Html::a('Изменить',['update','id'=>$id],['class'=>'btn btn-primary','role'=>'modal-remote'])
            ];
        }else{
            return $this->render('view', [
                'model' => $this->findModel($id),
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
                'upSearchModel' => $upSearchModel,
                'upDataProvider' => $upDataProvider,
                'downSearchModel' => $downSearchModel,
                'downDataProvider' => $downDataProvider,
            ]);
        }
    }

    /**
     * Creates a new Room model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new Room();

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Добавить комнату",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                        Html::button('Создать',['class'=>'btn btn-primary','type'=>"submit"])

                ];
            }else if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>'#pjax-card-container',
                    'title'=> "Добавить комнату",
                    'content'=>'<span class="text-success">Создание комнаты успешно завершено</span>',
                    'footer'=> Html::button('ОК',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                        Html::a('Создать еще',['create'],['class'=>'btn btn-primary','role'=>'modal-remote'])

                ];
            }else{
                return [
                    'title'=> "Добавить комнату",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                        Html::button('Создать',['class'=>'btn btn-primary','type'=>"submit"])

                ];
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }

    }

    /**
     * Updates an existing Room model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Изменить комнату #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                        Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];
            }else if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>'#pjax-card-container',
                    'forceClose' => true,
                ];
            }else{
                return [
                    'title'=> "Изменить комнату #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                        Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * @param int $id
     * @param string $rate
     * @return mixed
     */
    public function actionBuy($id, $rate)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $model = $this->findModel($id);
        $roomUser = new RoomUser([
            'room_id' => $id,
            'user_id' => Yii::$app->user->getId(),
            'rate' => $rate,
            'rate_type' => RoomUser::RATE_TYPE_UP,
        ]);

        if(time() > strtotime($model->datetime_accept_end)){
            return ['result' => false, 'message' => 'Прием ставок окончен'];
        }

        /** @var User $user */
        $user = Yii::$app->user->identity;
        if(($user->balance - $rate) < 0){
            return ['result' => false, 'message' => 'Недостаточно средств'];
        }

        $last = RoomUser::find()->where(['room_id' => $id, 'user_id' => Yii::$app->user->getId()])->one();

        if($last){
            return ['result' => false, 'message' => 'Вы уже поставили ставку'];
        }

        $user->balance = $user->balance - $rate;
        $user->reserve = $user->reserve + $rate;
        $user->save(false);
        $roomUser->save(false);

        $up =  RoomUser::find()->where(['room_id' => $roomUser->room_id, 'rate_type' => [RoomUser::RATE_TYPE_UP, RoomUser::RATE_TYPE_AWAIT_UP]])->sum('rate');
        $down =  RoomUser::find()->where(['room_id' => $roomUser->room_id, 'rate_type' => [RoomUser::RATE_TYPE_DOWN, RoomUser::RATE_TYPE_AWAIT_DOWN]])->sum('rate');

views/room/_columns.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use app\models\Room;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
        // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'id',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'name',
        'content' => function($model){
            return Html::a($model->name, ['room/view', 'id' => $model->id], ['data-pjax' => 0]);
        }
    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'room_setting_id',
//    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'datetime_accept_end',
        'format' => ['date', 'php:d.m.Y H:i:s'],
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'datetime_end',
        'format' => ['date', 'php:d.m.Y H:i:s'],
    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'service_commission',
//    ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'status',
         'value' => function($model){
            return ArrayHelper::getValue(Room::statusLabels(), $model->status);
         }
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'min_value',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'max_value',
     ],
//     [
//         'class'=>'\kartik\grid\DataColumn',
//         'attribute'=>'diff_rate_one',
//     ],
//     [
//         'class'=>'\kartik\grid\DataColumn',
//         'attribute'=>'diff_rate_two',
//     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'created_at',
         'format' => ['date', 'php:d.m.Y H:i:s'],
     ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'label'=>'Кол-во пользователей',
        'content' => function($model){
            $roomUsers = array_unique(ArrayHelper::getColumn(\app\models\RoomUser::find()->where(['room_id' => $model->id])->all(), 'user_id'));
            return count($roomUsers);
        }
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'label'=>'Кол-во ставок',
        'content' => function($model){
            return \app\models\RoomUser::find()->where(['room_id' => $model->id])->count();
        }
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'label'=>'Сумма ставок',
        'content' => function($model){
            return \app\models\RoomUser::find()->where(['room_id' => $model->id])->sum('rate');
        }
    ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'template' => '{update}{delete}',
        'visible' => Yii::$app->user->identity->isSuperAdmin(),
        'buttons' => [
            'delete' => function ($url, $model) {
                return Html::a('<i class="fa fa-trash text-danger" style="font-size: 16px;"></i>', $url, [
                    'role'=>'modal-remote', 'title'=>'Удалить',
                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                    'data-request-method'=>'post',
                    'data-confirm-title'=>'Вы уверены?',
                    'data-confirm-message'=>'Вы действительно хотите удалить данную запись?'
                ]);
            },
            'update' => function ($url, $model) {
                return Html::a('<i class="fa fa-pencil text-primary" style="font-size: 16px;"></i>', $url, [
                    'role'=>'modal-remote', 'title'=>'Изменить',
                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                    'data-request-method'=>'post',
                ])."&nbsp;";
            }
        ],
    ],

];   

views/room/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Room */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="room-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'room_setting_id')->textInput() ?>

    <?= $form->field($model, 'datetime_accept_end')->textInput() ?>

    <?= $form->field($model, 'datetime_end')->textInput() ?>

    <?= $form->field($model, 'service_commission')->textInput() ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <?= $form->field($model, 'min_value')->textInput() ?>

    <?= $form->field($model, 'max_value')->textInput() ?>

    <?= $form->field($model, 'diff_rate_one')->textInput() ?>

    <?= $form->field($model, 'diff_rate_two')->textInput() ?>

    <?= $form->field($model, 'created_at')->textInput() ?>

  
	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>

views/room/_rates_columns.php
<?php
use app\models\RoomUser;

return [
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'rate',
        'content' => function($model){
            if($model->rate_type == RoomUser::RATE_TYPE_UP){
                return "<span class='text-success'>{$model->rate}</span>";
            } else if($model->rate_type == RoomUser::RATE_TYPE_DOWN) {
                return "<span class='text-danger'>{$model->rate}</span>";
            }
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'label'=>'Очередь',
        'content' => function($model){
            if($model->rate_type == RoomUser::RATE_TYPE_AWAIT_UP){
                return "<span class='text-success'>{$model->rate}</span>";
            } else if($model->rate_type == RoomUser::RATE_TYPE_AWAIT_DOWN) {
                return "<span class='text-danger'>{$model->rate}</span>";
            }
        }
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'datetime_enter',
        'format' => ['date', 'php:d.m.Y H:i:s'],
    ],
];

views/room/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Room */

?>
<div class="room-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/room/index.php
<?php
use app\models\Room;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset;
use johnitvn\ajaxcrud\BulkButtonWidget;
use app\models\RoomUser;

/* @var $this yii\web\View */
/* @var $searchModel app\models\RoomSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = "Комнаты";
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>
    <div class="hidden">
        <div class="panel panel-inverse room-index">
            <div class="panel-heading">
                <!--        <div class="panel-heading-btn">-->
                <!--        </div>-->
                <h4 class="panel-title">Комнаты</h4>
            </div>
            <div class="panel-body">
                <div id="ajaxCrudDatatable">
                    <?=GridView::widget([
                        'id'=>'crud-datatable',
                        'dataProvider' => $dataProvider,
//            'filterModel' => $searchModel,
                        'pjax'=>true,
                        'columns' => require(__DIR__.'/_columns.php'),
                        'panelBeforeTemplate' => '',
                        'striped' => true,
                        'condensed' => true,
                        'responsive' => true,
                        'panel' => [
                            'headingOptions' => ['style' => 'display: none;'],
                            'after'=>BulkButtonWidget::widget([
                                    'buttons'=>Html::a('<i class="glyphicon glyphicon-trash"></i>&nbsp; Удалить',
                                        ["bulk-delete"] ,
                                        [
                                            "class"=>"btn btn-danger btn-xs",
                                            'role'=>'modal-remote-bulk',
                                            'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                                            'data-request-method'=>'post',
                                            'data-confirm-title'=>'Вы уверены?',
                                            'data-confirm-message'=>'Вы действительно хотите удалить данный элемент?'
                                        ]),
                                ]).
                                '<div class="clearfix"></div>',
                        ]
                    ])?>
                </div>
            </div>
        </div>
    </div>

<?php \yii\widgets\Pjax::begin(['id' => 'pjax-card-container']) ?>
<?php foreach ($dataProvider->models as $model): ?>
    <div class="col-md-4">
        <?php

        $panelClass = "custom-panel";

        $roomUser = $model->getCurrentUserRate();

        if($roomUser){
            if($roomUser->rate_type == RoomUser::RATE_TYPE_UP){
                $panelClass .= ' panel-success';
            } else if($roomUser->rate_type == RoomUser::RATE_TYPE_DOWN) {
                $panelClass .= ' panel-danger';
            }
        }

        ?>
        <div class="<?=$panelClass?>">
            <div class="row">
                <div class="<?=(Yii::$app->user->identity->isSuperAdmin() ? 'col-md-10' : 'col-md-12')?>">
                    <h4><?= Html::a($model->name, ['room/view', 'id' => $model->id], ['data-pjax' => 0]) ?> <span class="pull-right" style="font-weight: 600;"><?= ArrayHelper::getValue(Room::statusLabels(), $model->statusByTime) ?></span></h4>
                    <div class="custom-panel-content">
                        <div class="row">
                            <div class="col-md-8">
                                <p>До завершения приема заявок осталось: <b><?php
                                        //                                            echo Yii::$app->formatter->format($model->datetime_accept_end, ['date', 'php:d.m.Y H:i']);
                                        echo $model->getUntilDateTimeAcceptEndText();
                                        ?></b></p>
                                <p>До подведения итогов осталось: <b><?php
                                        //                                            echo Yii::$app->formatter->format($model->datetime_end, ['date', 'php:d.m.Y H:i']);
                                        echo $model->getUntilDateTimeEndText();
                                        ?></b></p>
                                <p><?=$model->getAttributeLabel('created_at')?>: <b><?= Yii::$app->formatter->format($model->created_at, ['date', 'php:d.m.Y H:i']) ?></b></p>
                                <p>Сумма кр: <b><?php
                                        echo round(RoomUser::find()->where(['room_id' => $model->id, 'rate_type' => RoomUser::RATE_TYPE_DOWN])->sum('rate'), 2);
                                        ?></b></p>
                            </div>
                            <div class="col-md-4">
                                <p>Кол-во пользователей: <b><?php
                                        $roomUsers = array_unique(ArrayHelper::getColumn(\app\models\RoomUser::find()->where(['room_id' => $model->id])->all(), 'user_id'));
                                        echo count($roomUsers);
                                        ?></b></p>
                                <p>Кол-во ставок: <b><?php
                                        echo \app\models\RoomUser::find()->where(['room_id' => $model->id])->count();
                                        ?></b></p>
                                <p>Сумма ставок: <b><?php
                                        echo round(\app\models\RoomUser::find()->where(['room_id' => $model->id])->sum('rate'), 2);
                                        ?></b></p>
                                <p>Сумма зел: <b><?php
                                        echo round(RoomUser::find()->where(['room_id' => $model->id, 'rate_type' => RoomUser::RATE_TYPE_UP])->sum('rate'), 2);
                                        ?></b></p>
                            </div>
                        </div>
                    </div>
                </div>
                <?php if(Yii::$app->user->identity->isSuperAdmin()): ?>
                    <div class="col-md-2">
                        <div class="custom-panel-btns pull-right">
                            <?= Html::a('<i class="fa fa-trash"></i>', ['room/delete', 'id' => $model->id], [
                                'class' => 'btn btn-danger btn-block pull-right',
                                'role'=>'modal-remote', 'title'=>'Удалить',
                                'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                                'data-request-method'=>'post',
                                'data-confirm-title'=>'Вы уверены?',
                                'data-confirm-message'=>'Вы действительно хотите удалить данную запись?'
                            ]); ?>
                            <?= Html::a('<i class="fa fa-pencil"></i>', ['room/update', 'id' => $model->id], [
                                'class' => 'btn btn-info btn-block pull-right',
                                'role'=>'modal-remote', 'title'=>'Изменить',
                                'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                                'data-request-method'=>'post',
                            ]); ?>
                            <?= Html::a('<i class="fa fa-eye"></i>', ['room/view', 'id' => $model->id], [
                                'class' => 'btn btn-success btn-block pull-right',
                                'data-pjax' => 0,
                            ]); ?>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php endforeach; ?>
<?php \yii\widgets\Pjax::end() ?>

<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

<?php

$script = <<< JS
setInterval(function(){
    $.pjax.reload('#pjax-card-container');
}, 45000);
JS;

$this->registerJs($script, \yii\web\View::POS_READY);


?>

views/room/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Room */
?>
<div class="room-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>